### ISSUE TITLE
error saving one to 0-1 relation

### ISSUE THREAD

**Issue by asbadawi** [bilal-fazlani/tracker-enabled-dbcontext#131]
at TrackerEnabledDbContext.Common.Auditors.LogAuditor.GetPrimaryKeyValuesOf(DbEntityEntry dbEntry, List`1 properties)
   at TrackerEnabledDbContext.Common.Auditors.LogAuditor.CreateLogRecord(Object userName, EventType eventType, ITrackerContext context, ExpandoObject metadata)
   at TrackerEnabledDbContext.Common.CoreTracker.AuditChanges(Object userName, ExpandoObject metadata)
   at TrackerEnabledDbContext.Identity.TrackerIdentityContext`6.SaveChanges(Object userName)

**Comment by bilal-fazlani** [comment]
Could you please provide more information.

**Comment by oleksiivasylenko** [comment]
I've just get exactly the same error. 

After all my "`EntityTracker.TrackAllProperties<OBJECT>();`" setups
I have a line with filter for modelBuilder 

`modelBuilder.Filter("IsDeleted", (ISoftDeletable d) => d.IsDeleted, false);`

The problem is that code tried to add new Item to repository with IsDeleted = true and it cause such error.
When I removed this filter or fix code not to save items which are isDeleted, everything works fine.
