### ISSUE TITLE
Given key was not present in the dictionary

### ISSUE THREAD

**Issue by attrib75** [bilal-fazlani/tracker-enabled-dbcontext#154]
This occurs now whenever I save anything, if I do not set GlobalTrackingConfig.Enabled = false;.  If i do set GlobalTrackingConfig.Enabled = false, nothing is tracked

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EntityFramework.MappingAPI.Mappers.MapperBase.BindForeignKeys() in c:\dev\EntityFramework.MappingAPI\trunk\src\EntityFramework.MappingAPI\Mappers\MapperBase.cs:line 618
   at EntityFramework.MappingAPI.Mappings.DbMapping..ctor(DbContext context) in c:\dev\EntityFramework.MappingAPI\trunk\src\EntityFramework.MappingAPI\Mappings\DbMapping.cs:line 103
   at EntityFramework.MappingAPI.EfMap.Get(DbContext context) in c:\dev\EntityFramework.MappingAPI\trunk\src\EntityFramework.MappingAPI\EfMap.cs:line 60
   at EntityFramework.MappingAPI.Extensions.MappingApiExtensions.Db(DbContext ctx, Type type) in c:\dev\EntityFramework.MappingAPI\trunk\src\EntityFramework.MappingAPI\Extensions\MappingApiExtensions.cs:line 51
   at TrackerEnabledDbContext.Common.Configuration.DbMapping..ctor(ITrackerContext context, Type entityType)
   at TrackerEnabledDbContext.Common.Auditors.LogAuditor.CreateLogRecord(Object userName, EventType eventType, ITrackerContext context, ExpandoObject metadata)
   at TrackerEnabledDbContext.Common.CoreTracker.AuditAdditions(Object userName, IEnumerable`1 addedEntries, ExpandoObject metadata)
   at CallSite.Target(Closure , CallSite , CoreTracker , Object , IEnumerable`1 , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at TrackerEnabledDbContext.TrackerContext.SaveChanges(Object userName)

**Comment by bilal-fazlani** [comment]
Could you please show how ur model looks like.

**Comment by attrib75** [comment]
Hi, thanks for responding.  We actually moved to another library.
