### ISSUE TITLE
Support with Efcore 7

### ISSUE THREAD

**Issue by Audhut** [bilal-fazlani/tracker-enabled-dbcontext#187]
Does this work with EFcore 7?
i get the below error

Could not load type 'Microsoft.EntityFrameworkCore.ModelExtensions' from assembly 'Microsoft.EntityFrameworkCore, Version=7.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

   at TrackerEnabledDbContext.Core.Common.Configuration.DbContextExtensions.GetKeyNames(DbContext context, Type entityType)
   at TrackerEnabledDbContext.Core.Common.Auditors.LogAuditor.CreateLogRecord(Object userName, EventType eventType, ITrackerContext context, ExpandoObject metadata)
   at TrackerEnabledDbContext.Core.Common.CoreTracker.AuditAdditions(Object userName, IEnumerable`1 addedEntries, ExpandoObject metadata)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at TrackerEnabledDbContext.Core.TrackerContext.<SaveChangesAsync>d__41.MoveNext()
   at Nwal.Infrastructure.Database.NwalDbContext.<SaveChangesAsync>d__17.MoveNext() in C:\Dev\git\NWAL\Nwal\Nwal.Infrastructure\Database\NwalDbContext.cs:line 27
   at Nwal.ProcessingService.NwalWorker.<StartAsync>d__4.MoveNext() in C:\Dev\git\NWAL\Nwal\Nwal.ProcessingService\NwalWorker.cs:line 38
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\Dev\git\NWAL\Nwal\Nwal.ProcessingService\Program.cs:line 31

**Comment by Audhut** [comment]
No longer valid as i was using a wrong package with the same name
