### ISSUE TITLE
Does not work with table splitted entities

### ISSUE THREAD

**Issue by dschuermans** [bilal-fazlani/tracker-enabled-dbcontext#91]
Hey,

I can't seem to get this working within a code-first project which uses table splitting to split a large table into several entities (http://weblogs.asp.net/manavi/associations-in-ef-4-1-code-first-part-4-table-splitting)

I've created a sample project demonstrating the issue.

The context:

```
public class MyDbContext : TrackerContext {
    public IDbSet<Person> Persons { get; set; }

    public MyDbContext() { } 

    protected override void OnModelCreating(DbModelBuilder modelBuilder) {
        modelBuilder.Configurations.Add(new PersonConfiguration());
        modelBuilder.Configurations.Add(new AddressConfiguration());
        base.OnModelCreating(modelBuilder);
    }
}
```

I went with a "person" object. On database level, it's a single table "Persons" but in my model, I have split off the address properties into a seperate "Address" entity:

```
public class Person
{
    protected Person() { }

    public Person(Address address)
    {
        if (address == null) throw new ArgumentNullException(nameof(address));
        Address = address;
        CreationDate = DateTime.Now;
        UpdateDate = DateTime.Now;
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public DateTime CreationDate { get; set; }
    public DateTime UpdateDate { get; set; }
    public virtual Address Address { get; set; }
}

public class Address
{
    protected Address() { }

    public Address(string street, string number, string zip, string state, string country)
    {
        if (String.IsNullOrWhiteSpace(street)) throw new ArgumentException("Argument is null or whitespace", nameof(street));
        if (String.IsNullOrWhiteSpace(number)) throw new ArgumentException("Argument is null or whitespace", nameof(number));
        if (String.IsNullOrWhiteSpace(zip)) throw new ArgumentException("Argument is null or whitespace", nameof(zip));
        if (String.IsNullOrWhiteSpace(state)) throw new ArgumentException("Argument is null or whitespace", nameof(state));
        if (String.IsNullOrWhiteSpace(country))
            throw new ArgumentException("Argument is null or whitespace", nameof(country));

        Street = street;
        Number = number;
        Zip = zip;
        State = state;
        Country = country;
    }

    public int Id { get; set; }
    public string Street { get; set; }
    public string Number { get; set; }
    public string Zip { get; set; }
    public string State { get; set; }
    public string Country { get; set; }
    public virtual  Person Person { get; set; }
}
```

These 2 entities have then be configured as such:

```
public class PersonConfiguration : EntityTypeConfiguration<Person>
{
    public PersonConfiguration()
    {
        HasKey(x => x.Id);
        HasRequired(x => x.Address)
            .WithRequiredPrincipal(x => x.Person);

        ToTable("Persons");
    }
}

public class AddressConfiguration : EntityTypeConfiguration<Address>
{
    public AddressConfiguration()
    {
        HasKey(x => x.Id);

        EntityTracker.TrackAllProperties<Address>();

        ToTable("Persons");
    }
}
```

This resulted in the following migration being scaffolded:

```
        CreateTable(
            "dbo.Persons",
            c => new
                {
                    Id = c.Int(nullable: false, identity: true),
                    Name = c.String(),
                    CreationDate = c.DateTime(nullable: false),
                    UpdateDate = c.DateTime(nullable: false),
                    Street = c.String(),
                    Number = c.String(),
                    Zip = c.String(),
                    State = c.String(),
                    Country = c.String(),
                })
            .PrimaryKey(t => t.Id);
```

When updating a person, specifically an Address property, EntityFramework.MappingApi will throw the following error:

`Unhandled Exception: System.Exception: Type 'ConsoleApplication1.database.entities.Address' is not found in context 'ConsoleApplication1.database.MyDbContext'
at EntityFramework.MappingAPI.Mappings.DbMapping.get_Item(String typeFullName) in c:\dev\EntityFramework.MappingAPI\trunk\src\EntityFramework.MappingAPI\Mappings\DbMapping.cs:line 131
at EntityFramework.MappingAPI.Mappings.DbMapping.get_Item(Type type) in c:\dev\EntityFramework.MappingAPI\trunk\src\EntityFramework.MappingAPI\Mappings\DbMapping.cs:line 118
at EntityFramework.MappingAPI.Extensions.MappingApiExtensions.Db(DbContext ctx, Type type) in c:\dev\EntityFramework.MappingAPI\trunk\src\EntityFramework.MappingAPI\Extensions\MappingApiExtensions.cs:line 51
at TrackerEnabledDbContext.Common.Configuration.DbMapping..ctor(ITrackerContext context, Type entityType)
at TrackerEnabledDbContext.Common.Auditors.LogAuditor.CreateLogRecord(Object userName, EventType eventType, ITrackerContext context)
at TrackerEnabledDbContext.Common.CoreTracker.AuditChanges(Object userName)
at TrackerEnabledDbContext.TrackerContext.SaveChanges(Object userName)`

I have tried adding the Address entity as a DbSet to the context as well, but no luck:

`Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
at System.Collections.Generic.Dictionary'2.get_Item(TKey key)
at EntityFramework.MappingAPI.Mappers.MapperBase.BindForeignKeys() in c:\dev\EntityFramework.MappingAPI\trunk\src\EntityFramework.MappingAPI\Mappers\MapperBase.cs:line 618
at EntityFramework.MappingAPI.Mappings.DbMapping..ctor(DbContext context) in c:\dev\EntityFramework.MappingAPI\trunk\src\EntityFramework.MappingAPI\Mappings\DbMapping.cs:line 103
at EntityFramework.MappingAPI.EfMap.Get(DbContext context) in c:\dev\EntityFramework.MappingAPI\trunk\src\EntityFramework.MappingAPI\EfMap.cs:line 60
at EntityFramework.MappingAPI.Extensions.MappingApiExtensions.Db(DbContext ctx, Type type) in c:\dev\EntityFramework.MappingAPI\trunk\src\EntityFramework.MappingAPI\Extensions\MappingApiExtensions.cs:line 51
at TrackerEnabledDbContext.Common.Configuration.DbMapping..ctor(ITrackerContext context, Type entityType)
at TrackerEnabledDbContext.Common.Auditors.LogAuditor.CreateLogRecord(Object userName, EventType eventType, ITrackerContext context)
at TrackerEnabledDbContext.Common.CoreTracker.AuditChanges(Object userName)
at TrackerEnabledDbContext.TrackerContext.SaveChanges(Object userName)`

When enabling tracking on the Person entity, it will work for those properties. (eg Name, CreationDate, UpdateDate)

Any ideas?
I'd hate having to resort to manually writing audit functionality :(

[ConsoleApplication1.zip](https://github.com/bilal-fazlani/tracker-enabled-dbcontext/files/157205/ConsoleApplication1.zip)

**Comment by dschuermans** [comment]
@bilal-fazlani it's been 11 days now, any thoughts?

**Comment by bilal-fazlani** [comment]
@dschuermans  hi,
As of now, I don't really have an idea about why it doesn't with table splitted entities. I downloaded your zip file but never got the time to debug through the code. And to be honest I don't when I will get that time. 

Would you be able to download the source code of this app and debug through the code ? If you fix the issue, I am open for pull requests.

Regards,
Bilal Fazlani
